### PR TITLE
Add a readme with installation instructions #2

### PR DESCRIPTION
**Pull request by ValchanOficial**
Add a readme with installation instructions #2

### CODE REVIEW

**Review by ottojo — CHANGES_REQUESTED** [review]
I dont think the "Add to Discord" section is neccessary, but if you remove that it looks good to merge!

**Review by ValchanOficial — COMMENTED** [review]
Section removed #2

**Review by ottojo — APPROVED** [review]

**Comment by ottojo** [comment]
Thanks for your contribution!

**Comment by ValchanOficial** [comment]
Thanks

**Pull request merged**
